on:
  push:
    branches: 
      - 'v6.4-rc6-clang-lto'
         
env:
  RELEASE_START: 1280 # 1150, as this is latest build by GitLab CI
  
jobs:
  build:
    runs-on: self-hosted
    permissions: write-all
    container: 
      image: gustavokch/rock64-release:arm64
      credentials:
        username: gustavokch
        password: dckr_pat_HzZm-FaY8cD_h88RZoEfhWTyC9A
      volumes:
        - /tmp/ccache:/tmp/ccache
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Docker binary
      run: |
        apt-get -y update
        apt-get -y install docker.io
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Reset ccache statistics
      run: | 
        export CCACHE_DIR=/tmp/ccache
        ccache -M 14G -F 0 -d /tmp/ccache
    - name: Build package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CCACHE_DIR: "/tmp/ccache"
      run: | 
        export PATH="/usr/lib/ccache/bin/:$PATH"
        ccache -M 14G -F 0 -d /tmp/ccache -s -v
        ccache --set-config=max_size=14.0G
        git config --global --add safe.directory "/__w/linux-mainline-kernel/linux-mainline-kernel"
        git config --global --add safe.directory "/__w/linux-rockchip/linux-rockchip"        
        export RELEASE=$(($RELEASE_START+$GITHUB_RUN_NUMBER))
        DEB_HOST_GNU_TYPE=aarch64-unknown-linux-gnu ./dev-make kernel-package
        export RELEASE_NAME="$(./dev-make version)"
        export RELEASE_TITLE="$(./dev-make version)"
        export DESCRIPTION="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        find / -type f -name "*.deb" > deb
        export DEB=$(cat deb)
        zip ../release.zip -@ < deb
        echo $RELEASE
        echo $RELEASE_TITLE
        echo $RELEASE_NAME
        gh release create --title $RELEASE_TITLE --generate-notes -R https://github.com/gustavokch/linux-mainline-kernel $RELEASE $DEB
        
    - uses: actions/upload-artifact@v3
      name: Upload Artifact
      with:
        name: release.zip
        path: ./release.zip
    - uses: actions/upload-artifact@v3
      name: Upload Artifact
      with:
        name: release.zip
        path: ../release.zip
        

    
