on:
  push:
    branches: 
      - 'release-6.13'
         
env:
  RELEASE_START: 1700 # 1150, as this is latest build by GitLab CI
  CCACHE_DIR: $RUNNER_TEMP/ccache

jobs:
  build:
    runs-on: self-hosted
    permissions: write-all
    container: 
      image: gustavokch/rock64build-release:latest
      credentials:
        username: gustavokch
        password: dckr_pat_HzZm-FaY8cD_h88RZoEfhWTyC9A
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Docker binary
      run: |
        apt-get -y update
        apt-get -y install docker.io

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Reset ccache statistics
      run: ccache -M 0 -F 0

    - name: Install build dependencies
      run: |
        sudo dpkg --add-architecture arm64
        sudo apt-get update
        sudo apt dist-upgrade -y
        # Core build tools
        sudo apt-get install -y \
          build-essential \
          devscripts \
          ccache \
          lsb-release \
          fakeroot \
          rsync \
          bc \
          flex \
          bison \
          libssl-dev \
          libelf-dev
    
        # Optional: multiarch targets (some builds require these explicitly)
        sudo apt-get install -y libssl-dev:arm64 libelf-dev:arm64
        sudo apt install debhelper -y
    - name: Build package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      run: |
        git config --global --add safe.directory "/__w/linux-mainline-kernel/linux-mainline-kernel"
        git config --global --add safe.directory "/__w/linux-rockchip/linux-rockchip"        
        export RELEASE=$(($RELEASE_START+$GITHUB_RUN_NUMBER))
        ./dev-make kernel-package
        export RELEASE_NAME="$(./dev-make version)"
        export RELEASE_TITLE="$(./dev-make version)"
        export DESCRIPTION="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        find / -type f -name "*.deb" > deb
        export DEB=$(cat deb)
        echo $RELEASE
        echo $RELEASE_TITLE
        echo $RELEASE_NAME
        gh release create --title $RELEASE_TITLE --generate-notes -R https://github.com/gustavokch/linux-mainline-kernel $RELEASE $DEB

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: .deb files
        path: ./*.deb
